
collections:
  gardening:
    output: true
    permalink: /gardening/:title
  recipes:
    output: true
    permalink: /recipes/:title
  writing:
    output: true
    permalink: /writing/:title

exclude: [templates, Gemfile, Gemfile.lock]